# Module 3: Data Structures Assignments
## Lesson 3.1: Lists
### Assignment 1: Creating and Accessing Lists

Create a list of the first 20 positive integers. Print the list.

### Assignment 2: Accessing List Elements

Print the first, middle, and last elements of the list created in Assignment 1.

### Assignment 3: List Slicing

Print the first five elements, the last five elements, and the elements from index 5 to 15 of the list created in Assignment 1.

### Assignment 4: List Comprehensions

Create a new list containing the squares of the first 10 positive integers using a list comprehension. Print the new list.

### Assignment 5: Filtering Lists

Create a new list containing only the even numbers from the list created in Assignment 1 using a list comprehension. Print the new list.

### Assignment 6: List Methods

Create a list of random numbers and sort it in ascending and descending order. Remove the duplicates from the list and print the modified list.

### Assignment 7: Nested Lists

Create a nested list representing a 3x3 matrix and print the matrix. Access and print the element at the second row and third column.

### Assignment 8: List of Dictionaries

Create a list of dictionaries where each dictionary represents a student with keys 'name' and 'score'. Sort the list of dictionaries by the 'score' in descending order and print the sorted list.

### Assignment 9: Matrix Transposition

Write a function that takes a 3x3 matrix (nested list) as input and returns its transpose. Print the original and transposed matrices.

### Assignment 10: Flattening a Nested List

Write a function that takes a nested list and flattens it into a single list. Print the original and flattened lists.

### Assignment 11: List Manipulation

Create a list of the first 10 positive integers. Remove the elements at indices 2, 4, and 6, and insert the element '99' at index 5. Print the modified list.

### Assignment 12: List Zipping

Create two lists of the same length. Use the `zip` function to combine these lists into a list of tuples and print the result.

### Assignment 13: List Reversal

Write a function that takes a list and returns a new list with the elements in reverse order. Print the original and reversed lists.

### Assignment 14: List Rotation

Write a function that rotates a list by n positions. Print the original and rotated lists.

### Assignment 15: List Intersection

Write a function that takes two lists and returns a new list containing only the elements that are present in both lists. Print the intersected list.

### Assignment 1: Creating and Accessing Lists

Create a list of the first 20 positive integers. Print the list.



In [14]:
List = list(range(1,21))
print(List) 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


### Assignment 2: Accessing List Elements

Print the first, middle, and last elements of the list created in Assignment 1.



In [9]:
mid = f"{List[int(len(List)/2) -1]} & { List[ int(len(List)/2)]}" if len(List)%2==0 else List[ int(len(List)/2)] 
print(List[0], mid, List[-1], sep=', ')

1, 10 & 11, 20


### Assignment 3: List Slicing

Print the first five elements, the last five elements, and the elements from index 5 to 15 of the list created in Assignment 1.



In [12]:
print(f"1st five : {List[:5]}\nlast five : {List[-5:]}\nindex 5 to 15 : {List[5:15]}")

1st five : [1, 2, 3, 4, 5]
last five : [16, 17, 18, 19, 20]
index 5 to 15 : [6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


### Assignment 4: List Comprehensions

Create a new list containing the squares of the first 10 positive integers using a list comprehension. Print the new list.



In [13]:
newlist = [i**2 for i in range(1,11)]
print(newlist)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


### Assignment 5: Filtering Lists

Create a new list containing only the even numbers from the list created in Assignment 1 using a list comprehension. Print the new list.



In [14]:
new_list = [j for j in List if j%2==0]
print(new_list)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


### Assignment 6: List Methods

Create a list of random numbers and sort it in ascending and descending order. Remove the duplicates from the list and print the modified list.

In [50]:
import random
rlist = [ random.randint(1,10) for k in range(10)]           #10 random no.s
print(f"original list : {rlist}")
nlist = list(set(rlist))
print(f"ascending : {sorted(nlist)} , descending : { sorted(nlist, reverse=True) }")

original list : [6, 6, 6, 9, 6, 7, 7, 8, 8, 10]
ascending : [6, 7, 8, 9, 10] , descending : [10, 9, 8, 7, 6]


### Assignment 7: Nested Lists

Create a nested list representing a 3x3 matrix and print the matrix. Access and print the element at the second row and third column.

In [5]:
import numpy as np
nestedlist = [ [1,2,3],
               [4,5,6],
               [7,8,9]]
print(np.array(nestedlist))
print(nestedlist[1][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


### Assignment 8: List of Dictionaries

Create a list of dictionaries where each dictionary represents a student with keys 'name' and 'score'. Sort the list of dictionaries by the 'score' in descending order and print the sorted list.



In [59]:
dictlist = [ {"name": "A", "score" : 45}, {"name": "B", "score" : 55}, {"name": "C", "score" : 25}, {"name": "D", "score" : 85} ]
dictlist.sort(key = lambda d : d['score'] , reverse=True)
print(dictlist)

[{'name': 'D', 'score': 85}, {'name': 'B', 'score': 55}, {'name': 'A', 'score': 45}, {'name': 'C', 'score': 25}]


### Assignment 9: Matrix Transposition

Write a function that takes a 3x3 matrix (nested list) as input and returns its transpose. Print the original and transposed matrices.



In [4]:
import numpy as np
def trasnposition(m):
    transposed = [ [], [], [] ]
    for i in m:
        for j in range(len(i)):
            transposed[j].append(i[j])
    return transposed

matrix = eval(input("enter a nested list of 3*3 matrix , like [ [...], [...], [...] ]"))
m_trans = trasnposition(matrix)
print(f"original matrix :\n{np.array(matrix)}")
print(f"\ntransposed matrix :\n{np.array(m_trans)}")

original matrix :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

transposed matrix :
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Assignment 10: Flattening a Nested List

Write a function that takes a nested list and flattens it into a single list. Print the original and flattened lists.



In [7]:
def flat_list(nestl):
    fl = []
    for x in nestl :
        fl.extend(x)
    return fl

nestlist = eval(input("enter a nested list , like [ [...], [...], [...], .....]"))
flatlist = flat_list(nestlist)
print(f"original list : {nestlist} \nflattened list : {flatlist}")

original list : [[1, 2, 3], [4, 5, 6], [7, 8, 9]] 
flattened list : [1, 2, 3, 4, 5, 6, 7, 8, 9]


### Assignment 11: List Manipulation

Create a list of the first 10 positive integers. Remove the elements at indices 2, 4, and 6, and insert the element '99' at index 5. Print the modified list.



In [18]:
list_ = list(range(1,11)) 
print(f"original list : {list_}") 
list_.pop(6)
list_.pop(4)
list_.pop(2)
list_.insert(5, '99')
print(f"modified list : {list_}")

original list : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
modified list : [1, 2, 4, 6, 8, '99', 9, 10]


### Assignment 12: List Zipping

Create two lists of the same length. Use the `zip` function to combine these lists into a list of tuples and print the result.

In [19]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list_new = list(zip(list1, list2))
print(list_new)

[(1, 6), (2, 7), (3, 8), (4, 9), (5, 10)]


### Assignment 13: List Reversal

Write a function that takes a list and returns a new list with the elements in reverse order. Print the original and reversed lists.



In [ ]:
def list_reversal(l):
    Newlist = l.copy() 
    Newlist.reverse()
    return Newlist

orglist = eval(input("enter a list in [...] manner"))
reversed_list = list_reversal(orglist)
print(f"original list : {orglist} \nreversed list : {reversed_list}")

original list : [1, 2, 4, 8, 16] 
reversed list : [16, 8, 4, 2, 1]


### Assignment 14: List Rotation

Write a function that rotates a list by n positions. Print the original and rotated lists.



In [31]:
def left_rotate(x,n):
    lr = x[n:] + x[:n]
    return lr
def right_rotate(x,n):
    rr = x[-n:] + x[:-n]
    return rr

Lst = eval(input("enter a list in [...] manner"))
n = int(input("enter position no."))
print(f"original list : {Lst}")
leftL, rightL = left_rotate(Lst,n), right_rotate(Lst,n)
print(f"rotated list left by {n} position : {leftL}")
print(f"rotated list right by {n} position : {rightL}")

original list : [1, 2, 3, 4, 5, 6, 7]
rotated list left by 3 position : [4, 5, 6, 7, 1, 2, 3]
rotated list right by 3 position : [5, 6, 7, 1, 2, 3, 4]


### Assignment 15: List Intersection

Write a function that takes two lists and returns a new list containing only the elements that are present in both lists. Print the intersected list.

In [ ]:
def intersection(a,b):
    ilist = [ele for ele in a if ele in b]
    ilist.sort()
    return list(set(ilist))

listA = eval(input("enter list 1 in [...] manner"))
listB = eval(input("enter list 2 in [...] manner"))
print(f"list1 : {listA} \nlist2 : {listB}")
intersected = intersection(listA, listB)
print(f"intersected list : {intersected}")

list1 : [1, 2, 5, 4, 7, 59, 522, 5, 6, 4, 8] 
list2 : [1, 2, 3, 4, 5, 96]
intersected list : [1, 2, 4, 5]
